# Generated by Django 5.1.4 on 2024-12-21 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='resume',
            field=models.TextField(blank=True, null=True),
        ),
    ]
