# Generated by Django 5.1.4 on 2024-12-21 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id_ordonnance', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('valide', 'Valide'), ('non_valide', 'Non valide')], default='non_valide', max_length=10)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordonnances', to='consultations.consultation')),
            ],
        ),
    ]
