# Generated by Django 5.1.4 on 2025-01-04 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordonnance', '0003_alter_ordonnance_consultation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordonnance',
            name='status',
        ),
    ]
