# Generated by Django 5.1.4 on 2024-12-20 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bilans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyseBiologique',
            fields=[
                ('id_analyse_biologique', models.AutoField(primary_key=True, serialize=False)),
                ('parametre_analyse', models.CharField(choices=[('Fer', 'Fer'), ('Hypertension', 'Hypertension'), ('Glycémie', 'Glycémie')], max_length=50)),
                ('valeur', models.FloatField()),
                ('unite', models.CharField(choices=[('mg/m3', 'mg/m3'), ('µmol/litre', 'µmol/litre'), ('mmol/24h', 'mmol/24h')], max_length=20)),
                ('bilan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses_biologiques', to='bilans.bilan')),
                ('laborantin', models.ForeignKey(limit_choices_to={'role': 'laborantin'}, on_delete=django.db.models.deletion.CASCADE, related_name='analyses_biologiques', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
