# Generated by Django 5.1.4 on 2024-12-21 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicaments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdonnanceHasMedicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose', models.FloatField()),
                ('duree', models.IntegerField()),
                ('frequence', models.IntegerField()),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordonnance_has_medicaments', to='medicaments.medicament')),
            ],
        ),
    ]
