# Generated by Django 5.1.4 on 2024-12-21 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ordonnace_has_medicament', '0001_initial'),
        ('ordonnance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordonnancehasmedicament',
            name='ordonnance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordonnance_has_medicaments', to='ordonnance.ordonnance'),
        ),
    ]
