# Generated by Django 5.1.4 on 2024-12-27 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordonnace_has_medicament', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordonnancehasmedicament',
            name='dose',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='ordonnancehasmedicament',
            name='duree',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='ordonnancehasmedicament',
            name='frequence',
            field=models.CharField(max_length=15),
        ),
    ]
