# Generated by Django 5.1.4 on 2024-12-17 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DPI', '0004_alter_dpi_nss_alter_dpi_personne_contact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Soin',
            fields=[
                ('id_soin', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('soins', models.CharField(max_length=255)),
                ('observations', models.TextField(blank=True, null=True)),
                ('dpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soins', to='DPI.dpi')),
                ('infirmier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soins_realises', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
