# Generated by Django 5.1.4 on 2024-12-20 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bilan',
            fields=[
                ('id_bilan', models.AutoField(primary_key=True, serialize=False)),
                ('type_bilan', models.CharField(choices=[('radiologique', 'Radiologique'), ('biologique', 'Biologique')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bilans', to='consultations.consultation')),
            ],
        ),
    ]
