# Generated by Django 5.1.4 on 2024-12-21 22:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilans', '0001_initial'),
        ('consultations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyseBiologique',
            fields=[
                ('id_analyse_biologique', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=45)),
                ('date', models.DateField()),
                ('parametre_analyse', models.CharField(max_length=100)),
                ('valeur', models.FloatField()),
                ('unite', models.CharField(max_length=10)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses_biologiques', to='consultations.consultation')),
                ('laborantin', models.OneToOneField(limit_choices_to={'role': 'laborantin'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImageRadiologique',
            fields=[
                ('id_image_radiologique', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=45)),
                ('date', models.DateField()),
                ('url', models.URLField(max_length=1000)),
                ('compte_rendu', models.TextField()),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_radiologiques', to='consultations.consultation')),
                ('radiologue', models.OneToOneField(limit_choices_to={'role': 'radiologue'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Bilan',
        ),
    ]
