# Generated by Django 5.1.4 on 2024-12-21 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bilans', '0002_analysebiologique_imageradiologique_delete_bilan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysebiologique',
            name='date',
        ),
        migrations.RemoveField(
            model_name='imageradiologique',
            name='date',
        ),
    ]
