# Generated by Django 5.1.4 on 2024-12-21 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilans', '0003_remove_analysebiologique_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysebiologique',
            name='parametre_analyse',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='analysebiologique',
            name='unite',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='analysebiologique',
            name='valeur',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='imageradiologique',
            name='compte_rendu',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='imageradiologique',
            name='type',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='imageradiologique',
            name='url',
            field=models.URLField(max_length=1000, null=True),
        ),
    ]
