# Generated by Django 5.1.4 on 2024-12-21 22:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilans', '0004_alter_analysebiologique_parametre_analyse_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysebiologique',
            name='laborantin',
            field=models.OneToOneField(limit_choices_to={'role': 'laborantin'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='imageradiologique',
            name='radiologue',
            field=models.OneToOneField(limit_choices_to={'role': 'radiologue'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
