# Generated by Django 5.1.4 on 2024-12-22 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilans', '0005_alter_analysebiologique_laborantin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysebiologique',
            name='laborantin',
            field=models.ForeignKey(limit_choices_to={'role': 'laborantin'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analyses_biologiques', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='imageradiologique',
            name='radiologue',
            field=models.ForeignKey(limit_choices_to={'role': 'radiologue'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images_radiologiques', to=settings.AUTH_USER_MODEL),
        ),
    ]
