# Generated by Django 5.1.4 on 2024-12-27 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilans', '0006_alter_analysebiologique_laborantin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysebiologique',
            name='statut',
            field=models.CharField(choices=[('terminé', 'Terminé'), ('pas_terminé', 'Pas_terminé')], default='pas_terminé', max_length=15),
        ),
        migrations.AddField(
            model_name='imageradiologique',
            name='statut',
            field=models.CharField(choices=[('terminé', 'Terminé'), ('pas_terminé', 'Pas_terminé')], default='pas_terminé', max_length=15),
        ),
    ]
