# Generated by Django 5.1.4 on 2024-12-27 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilans', '0007_analysebiologique_statut_imageradiologique_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysebiologique',
            name='valeur',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
