# Generated by Django 5.1.4 on 2024-12-17 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DPI',
            fields=[
                ('nss', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('date_naissance', models.DateField()),
                ('telephone', models.CharField(max_length=15)),
                ('adresse', models.CharField(max_length=255)),
                ('mutuelle', models.CharField(max_length=100)),
                ('personne_contact', models.CharField(max_length=255)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin'), ('O', 'Autre')], max_length=1)),
                ('patient', models.OneToOneField(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
