# Generated by Django 5.1.4 on 2024-12-17 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dpi',
            old_name='patient',
            new_name='patient_id',
        ),
    ]
