# Generated by Django 5.1.4 on 2024-12-17 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DPI', '0002_rename_patient_dpi_patient_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dpi',
            old_name='patient_id',
            new_name='patient',
        ),
    ]
