# Generated by Django 5.1.4 on 2024-12-17 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DPI', '0003_rename_patient_id_dpi_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dpi',
            name='nss',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dpi',
            name='personne_contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
