# Generated by Django 5.1.4 on 2024-12-22 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DPI', '0004_alter_dpi_nss_alter_dpi_personne_contact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dpi',
            name='medecin_traitant',
            field=models.OneToOneField(blank=True, limit_choices_to={'role': 'medecin'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dpi_as_medecin_traitant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dpi',
            name='patient',
            field=models.OneToOneField(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='dpi_as_patient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dpi',
            name='sexe',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1),
        ),
    ]
