# Generated by Django 5.1.4 on 2024-12-22 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DPI', '0006_remove_dpi_nom'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dpi',
            name='medecin_traitant',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'medecin'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dpi_as_medecin_traitant', to=settings.AUTH_USER_MODEL),
        ),
    ]
