# Generated by Django 5.1.4 on 2025-01-04 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicaments', '0001_initial'),
        ('ordonnance', '0004_remove_ordonnance_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicament',
            name='code',
        ),
        migrations.RemoveField(
            model_name='medicament',
            name='forme',
        ),
        migrations.AddField(
            model_name='medicament',
            name='dose',
            field=models.CharField(default=100, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicament',
            name='duree',
            field=models.CharField(default=2, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicament',
            name='ordonnance',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='medicaments', to='ordonnance.ordonnance'),
            preserve_default=False,
        ),
    ]
