# Generated by Django 5.1.4 on 2025-01-04 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicaments', '0002_remove_medicament_code_remove_medicament_forme_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicament',
            name='nom',
            field=models.CharField(max_length=255),
        ),
    ]
